<?php

use Symfony\Component\Form\Extension\Core\Type;
use Ajaxy\Forms\Inc\Types;

return [
    'text' => [
        "label" => "Text",
        "class" => Type\TextType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/text.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim"],
        "properties" => [],
        "order" => 1,
        "keywords" => "text,short,small,string,textfield,paragraph",
        "common" => true
    ],
    'textarea' => [
        "label" => "Textarea",
        "class" => Type\TextareaType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/textarea.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim"],
        "properties" => [],
        "order" => 2,
        "keywords" => "textarea,long,medium,text,paragraph",
        "common" => true
    ],
    'email' => [
        "label" => "Email",
        "class" => Type\EmailType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/email.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [],
        "order" => 3,
        "keywords" => "email",
        "common" => true
    ],
    'integer' => [
        "label" => "Integer",
        "class" => Type\IntegerType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/integer.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 6,
                "type" => "checkbox",
                "label" => "Grouping",
                "name" => "grouping",
                "help" => "Numbers will be grouped with a comma or period (depending on your locale): 12345.123 would display as 12,345.123",
            ],
            [
                "section" => "basic",
                "order" => 7,
                "type" => "select",
                "name" => "rounding_mode",
                "label" => "Rounding Mode",
                "options" => [
                    "" => 'Select a rounding mode',
                    \NumberFormatter::ROUND_DOWN => "Round towards zero",
                    \NumberFormatter::ROUND_FLOOR => "Round towards negative infinity",
                    \NumberFormatter::ROUND_UP => "Round away from zero",
                    \NumberFormatter::ROUND_CEILING => "Round towards positive infinity"
                ],
                "help" => "By default, if the user enters a non-integer number, it will be rounded down",
            ]
        ],
        "order" => 30,
        "keywords" => "integer,number,float",
        "common" => false
    ],
    'money' => [
        "label" => "Money",
        "class" => Type\MoneyType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/money.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 6,
                "type" => "text",
                "name" => "currency",
                "label" => "Currency",
                "help" => 'This can be any <a href="https://en.wikipedia.org/wiki/ISO_4217" target="_blank">3 letter ISO 4217 code</a>. You can also set this to false to hide the currency symbol.',
            ],
            [
                "section" => "basic",
                "order" => 7,
                "type" => "checkbox",
                "label" => "Grouping",
                "name" => "grouping",
                "help" => "Numbers will be grouped with a comma or period (depending on your locale): 12345.123 would display as 12,345.123",
            ],
            [
                "section" => "basic",
                "order" => 8,
                "type" => "select",
                "name" => "rounding_mode",
                "label" => "Rounding Mode",
                "options" => [
                    "" => 'Select a rounding mode',
                    \NumberFormatter::ROUND_DOWN => "Round towards zero",
                    \NumberFormatter::ROUND_FLOOR => "Round towards negative infinity",
                    \NumberFormatter::ROUND_UP => "Round away from zero",
                    \NumberFormatter::ROUND_CEILING => "Round towards positive infinity"
                ],
                "help" => "By default, if the user enters a non-integer number, it will be rounded down",
            ],
            [
                "section" => "advanced",
                "order" => 6,
                "type" => "number",
                "name" => "divisor",
                "label" => "Divisor",
                "default" => 1,
                "help" => 'If you need to divide your starting value by a number before rendering it to the user, you can use the divisor option',
            ],
            [
                "section" => "advanced",
                "order" => 6,
                "type" => "number",
                "name" => "scale",
                "label" => "Scale",
                "default" => 2,
                "help" => 'If, for some reason, you need some scale other than 2 decimal places, you can modify this value',
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "type" => "checkbox",
                "name" => "html5",
                "label" => "Native HTML5",
                "default" => 1,
                "help" => 'If set to true, the HTML input will be rendered as a native HTML5',
            ]
        ],
        "order" => 31,
        "keywords" => "money,currency,dollar,euro,pound,yen",
        "common" => false
    ],
    'number' => [
        "label" => "Number",
        "class" => Type\NumberType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/number.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 7,
                "type" => "checkbox",
                "label" => "Grouping",
                "name" => "grouping",
                "help" => "Numbers will be grouped with a comma or period (depending on your locale): 12345.123 would display as 12,345.123",
            ],
            [
                "section" => "basic",
                "order" => 8,
                "type" => "select",
                "name" => "rounding_mode",
                "label" => "Rounding Mode",
                "options" => [
                    "" => 'Select a rounding mode',
                    \NumberFormatter::ROUND_DOWN => "Round towards zero",
                    \NumberFormatter::ROUND_FLOOR => "Round towards negative infinity",
                    \NumberFormatter::ROUND_UP => "Round away from zero",
                    \NumberFormatter::ROUND_CEILING => "Round towards positive infinity"
                ],
                "help" => "By default, if the user enters a non-integer number, it will be rounded down",
            ],
            [
                "section" => "advanced",
                "order" => 6,
                "type" => "number",
                "name" => "divisor",
                "label" => "Divisor",
                "default" => 1,
                "help" => 'If you need to divide your starting value by a number before rendering it to the user, you can use the divisor option',
            ],
            [
                "section" => "advanced",
                "order" => 6,
                "type" => "number",
                "name" => "scale",
                "label" => "Scale",
                "default" => 2,
                "help" => 'If, for some reason, you need some scale other than 2 decimal places, you can modify this value',
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "type" => "checkbox",
                "name" => "html5",
                "label" => "Native HTML5",
                "default" => 0,
                "help" => 'If set to true, the HTML input will be rendered as a native HTML5',
            ]
        ],
        "order" => 4,
        "keywords" => "number,integer,float",
        "common" => true
    ],
    'password' => [
        "label" => "Password",
        "class" => Type\PasswordType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/password.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "default" => true,
                "type" => "checkbox",
                "label" => "Always Empty",
                "name" => "always_empty",
                "help" => "If set to true, the field will always render blank, even if the corresponding field has a value.",
            ]
        ],
        "order" => 33,
        "keywords" => "password",
        "common" => false
    ],
    'percent' => [
        "label" => "Percent",
        "class" => Type\PercentType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/percent.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 8,
                "type" => "select",
                "name" => "rounding_mode",
                "label" => "Rounding Mode",
                "options" => [
                    "" => 'Select a rounding mode',
                    \NumberFormatter::ROUND_DOWN => "Round towards zero",
                    \NumberFormatter::ROUND_FLOOR => "Round towards negative infinity",
                    \NumberFormatter::ROUND_UP => "Round away from zero",
                    \NumberFormatter::ROUND_CEILING => "Round towards positive infinity"
                ],
                "help" => "By default, if the user enters a non-integer number, it will be rounded down",
            ],
            [
                "section" => "advanced",
                "order" => 6,
                "type" => "text",
                "name" => "symbol",
                "label" => "Symbol",
                "default" => "%",
                "help" => 'By default, fields are rendered with a percentage sign % after the input. Setting the value to empty will not display the percentage sign',
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "type" => "number",
                "name" => "scale",
                "label" => "Scale",
                "default" => 2,
                "help" => 'If, for some reason, you need some scale other than 2 decimal places, you can modify this value',
            ],
            [
                "section" => "advanced",
                "order" => 8,
                "type" => "select",
                "name" => "type",
                "label" => "Type",
                "default" => "fractional",
                "options" => [
                    "fractional" => "Fractional",
                    "integer" => "Integer"
                ],
                "help" => 'If set to true, the HTML input will be rendered as a native HTML5',
            ],
            [
                "section" => "advanced",
                "order" => 8,
                "type" => "checkbox",
                "name" => "html5",
                "label" => "Native HTML5",
                "default" => 1,
                "help" => 'If set to true, the HTML input will be rendered as a native HTML5',
            ]
        ],
        "order" => 33,
        "keywords" => "percent",
        "common" => false
    ],
    'search' => [
        "label" => "Search",
        "class" => Type\SearchType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/search.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [],
        "order" => 33,
        "keywords" => "search",
        "common" => false
    ],
    'url' => [
        "label" => "URL",
        "class" => Type\UrlType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/url.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 9,
                "type" => "text",
                "name" => "default_protocol",
                "label" => "Default Protocol",
                "default" => "http",
                "help" => "If a value is submitted that doesn't begin with some protocol (e.g. http://, ftp://, etc), this protocol will be prepended to the string when the data is submitted to the form.",
            ],
        ],
        "order" => 33,
        "keywords" => "url,http,https,protocol",
        "common" => false
    ],
    'posts' => [
        "label" => "Posts",
        "class" => Types\PostType::class,
        "docs" => "",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 2,
                "type" => "select",
                "name" => "post_type",
                "options" => function () {
                    return Types\Data\Posts::getPostTypes();
                },
                "label" => "Post Type",
                "help" => "The post type from which to retrieve posts",
            ],
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "default_option",
                "label" => "Default Option",
                "help" => "if set it will show as default option",
            ],
            [
                "section" => "basic",
                "order" => 3,
                "type" => "number",
                "name" => "numberposts",
                "default" => "-1",
                "label" => "Limit Posts",
                "help" => "if set it will limit total posts, use (-1) to get all posts",
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "number",
                "name" => "category",
                "default" => "0",
                "label" => "Category ID",
                "help" => "if set it will limit total posts to specific category",
            ],
            [
                "section" => "basic",
                "order" => 6,
                "type" => "select",
                "name" => "orderby",
                "default" => "date",
                "label" => "Order By",
                "options" => [
                    "date" => "Date",
                    "title" => "Title",
                    "name" => "Name",
                    "author" => "Author",
                    "comment_count" => "Comment Count",
                    "menu_order" => "Menu Order",
                    "meta_value" => "Meta Value",
                    "meta_value_num" => "Meta Value Number",
                    "post__in" => "Post In",
                    "post_name__in" => "Post Name In",
                    "post_parent" => "Post Parent",
                    "post_type" => "Post Type",
                    "rand" => "Random",
                    "relevance" => "Relevance",
                    "modified" => "Modified",
                ],
                "default" => "date",
                "help" => "Ordering the results shown",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "select",
                "name" => "order",
                "default" => "DESC",
                "label" => "Order",
                "options" => [
                    "ASC" => "Ascending",
                    "DESC" => "Descending"
                ],
                "help" => "Sorting order of the results",
            ],
            [
                "section" => "basic",
                "order" => 6,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "type" => "text",
                "name" => "include",
                "label" => "Include",
                "help" => "Include specific post IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 8,
                "type" => "text",
                "name" => "exclude",
                "label" => "Exclude",
                "help" => "Exclude specific post IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 9,
                "type" => "text",
                "name" => "meta_key",
                "label" => "Meta Key",
                "help" => "The meta key to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 10,
                "type" => "text",
                "name" => "meta_value",
                "label" => "Meta Value",
                "help" => "The meta value to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 11,
                "type" => "text",
                "name" => "post_status",
                "label" => "Post Status",
                "default" => "publish",
                "help" => "The status of the post",
            ],
            [
                "section" => "advanced",
                "order" => 12,
                "type" => "checkbox",
                "name" => "suppress_filters",
                "label" => "Suppress Filters",
                "help" => "Whether to suppress filters",
            ]
        ],
        "order" => 33,
        "keywords" => "posts,custom post types, post_type",
        "common" => true
    ],
    'terms' => [
        "label" => "Terms",
        "class" => Types\TermType::class,
        "docs" => "",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "select",
                "name" => "taxonomy",
                "options" => function () {
                    return Types\Data\Terms::getTaxonomies();
                },
                "label" => "Taxonomy",
                "help" => "The taxonomy from which to retrieve terms",
            ],
            [
                "section" => "basic",
                "order" => 2,
                "type" => "text",
                "name" => "default_option",
                "label" => "Default Option",
                "help" => "if set it will show as default option",
            ],
            [
                "section" => "basic",
                "order" => 3,
                "type" => "number",
                "name" => "number",
                "default" => "",
                "label" => "Limit",
                "help" => "if set it will limit total terms",
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "object_ids",
                "label" => "Object IDs",
                "help" => "if set it will limit total terms to specific term IDs",
                "default" => "",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "select",
                "name" => "orderby",
                "default" => "name",
                "label" => "Order By",
                "options" => [
                    "name" => "Name",
                    "slug" => "Slug",
                    "term_group" => "Term Group",
                    "term_id" => "Term ID",
                    "id" => "ID",
                    "description" => "Description",
                    "parent" => "Parent",
                    "count" => "Count",
                    "none" => "None"
                ],
                "help" => "Ordering the results shown",
            ],
            [
                "section" => "basic",
                "order" => 6,
                "type" => "select",
                "name" => "order",
                "default" => "ASC",
                "label" => "Order",
                "options" => [
                    "ASC" => "Ascending",
                    "DESC" => "Descending"
                ],
                "help" => "Sorting order of the results",
            ],
            [
                "section" => "basic",
                "order" => 6,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "type" => "text",
                "name" => "include",
                "label" => "Include",
                "help" => "Include specific term IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 8,
                "type" => "text",
                "name" => "exclude",
                "label" => "Exclude",
                "help" => "Exclude specific term IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 9,
                "type" => "text",
                "name" => "exclude_tree",
                "label" => "Exclude Tree",
                "help" => "Exclude all terms that are descendants of the specified term IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 10,
                "type" => "number",
                "name" => "offset",
                "label" => "Offset",
                "help" => "The number of terms to skip",
            ],
            [
                "section" => "advanced",
                "order" => 11,
                "type" => "number",
                "name" => "child_of",
                "label" => "Child Of",
                "help" => "Only include terms that are direct children of the specified term ID. If this is 0, the term will be included regardless of its parent.",
            ],
            [
                "section" => "advanced",
                "order" => 12,
                "type" => "text",
                "name" => "meta_key",
                "label" => "Meta Key",
                "help" => "The meta key to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 13,
                "type" => "text",
                "name" => "meta_value",
                "label" => "Meta Value",
                "help" => "The meta value to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 14,
                "type" => "text",
                "name" => "meta_compare",
                "label" => "Meta Compare",
                "help" => "The comparison operator to use for the meta value",
            ],
            [
                "section" => "advanced",
                "order" => 17,
                "type" => "text",
                "name" => "hide_empty",
                "label" => "Hide Empty",
                "help" => "Whether to hide terms not assigned to any posts",
            ]
        ],
        "order" => 33,
        "keywords" => "terms,taxonomy",
        "common" => true
    ],
    'term_posts' => [
        "label" => "Term Posts",
        "class" => Types\TermPostsType::class,
        "docs" => "",
        "disable_constraints" => true,
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "select",
                "name" => "taxonomy",
                "options" => function () {
                    return Types\Data\Terms::getTaxonomies();
                },
                "label" => "Taxonomy",
                "help" => "The taxonomy from which to retrieve terms",
            ],
            [
                "section" => "basic",
                "order" => 2,
                "type" => "text",
                "name" => "default_option",
                "label" => "Default Option",
                "help" => "if set it will show as default option",
            ],
            [
                "section" => "advanced",
                "order" => 3,
                "type" => "number",
                "name" => "number",
                "default" => "",
                "label" => "Limit",
                "help" => "if set it will limit total terms",
            ],
            [
                "section" => "advanced",
                "order" => 4,
                "type" => "text",
                "name" => "object_ids",
                "label" => "Object IDs",
                "help" => "if set it will limit total terms to specific term IDs",
                "default" => "",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "select",
                "name" => "orderby",
                "default" => "name",
                "label" => "Order By",
                "options" => [
                    "name" => "Name",
                    "slug" => "Slug",
                    "term_group" => "Term Group",
                    "term_id" => "Term ID",
                    "id" => "ID",
                    "description" => "Description",
                    "parent" => "Parent",
                    "count" => "Count",
                    "none" => "None"
                ],
                "help" => "Ordering the results shown",
            ],
            [
                "section" => "basic",
                "order" => 6,
                "type" => "select",
                "name" => "order",
                "default" => "ASC",
                "label" => "Order",
                "options" => [
                    "ASC" => "Ascending",
                    "DESC" => "Descending"
                ],
                "help" => "Sorting order of the results",
            ],
            [
                "section" => "basic",
                "order" => 2,
                "type" => "select",
                "name" => "post_type",
                "options" => function () {
                    return Types\Data\Posts::getPostTypes();
                },
                "label" => "Post Type",
                "help" => "The post type from which to retrieve posts",
            ],
            [
                "section" => "basic",
                "order" => 3,
                "type" => "text",
                "name" => "post_placeholder",
                "label" => "Post Default Option",
                "help" => "if set it will show as default option",
            ],
            [
                "section" => "basic",
                "order" => 6,
                "type" => "select",
                "name" => "post_orderby",
                "default" => "date",
                "label" => "Post Order By",
                "options" => [
                    "date" => "Date",
                    "title" => "Title",
                    "name" => "Name",
                    "comment_count" => "Comment Count",
                    "menu_order" => "Menu Order",
                    "post_parent" => "Post Parent",
                    "post_type" => "Post Type",
                    "rand" => "Random",
                    "relevance" => "Relevance",
                    "modified" => "Modified",
                ],
                "default" => "date",
                "help" => "Ordering the results shown",
            ],
            [
                "section" => "basic",
                "order" => 7,
                "type" => "select",
                "name" => "post_order",
                "default" => "DESC",
                "label" => "Post Order",
                "options" => [
                    "ASC" => "Ascending",
                    "DESC" => "Descending"
                ],
                "help" => "Sorting order of the results",
            ],
            [
                "section" => "basic",
                "order" => 8,
                "type" => "text",
                "name" => "loading_message",
                "default" => "",
                "label" => "Loading Message",
                "help" => "if set it will show loading message",
            ],
            [
                "section" => "basic",
                "order" => 9,
                "type" => "text",
                "name" => "not_found_message",
                "default" => "",
                "label" => "Not Found Message",
                "help" => "if set it will show when there is no posts found",
            ],
            [
                "section" => "basic",
                "order" => 10,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "type" => "text",
                "name" => "post_include",
                "label" => "Post Include",
                "help" => "Include specific post IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 8,
                "type" => "text",
                "name" => "post_exclude",
                "label" => "Post Exclude",
                "help" => "Exclude specific post IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 9,
                "type" => "text",
                "name" => "post_meta_key",
                "label" => "Post Meta Key",
                "help" => "The meta key to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 10,
                "type" => "text",
                "name" => "post_meta_value",
                "label" => "Post Meta Value",
                "help" => "The meta value to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 11,
                "type" => "text",
                "name" => "post_status",
                "label" => "Post Status",
                "default" => "publish",
                "help" => "The status of the post",
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "type" => "text",
                "name" => "include",
                "label" => "Include",
                "help" => "Include specific term IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 8,
                "type" => "text",
                "name" => "exclude",
                "label" => "Exclude",
                "help" => "Exclude specific term IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 9,
                "type" => "text",
                "name" => "exclude_tree",
                "label" => "Exclude Tree",
                "help" => "Exclude all terms that are descendants of the specified term IDs. Separate multiple IDs with commas.",
            ],
            [
                "section" => "advanced",
                "order" => 10,
                "type" => "number",
                "name" => "offset",
                "label" => "Offset",
                "help" => "The number of terms to skip",
            ],
            [
                "section" => "advanced",
                "order" => 11,
                "type" => "number",
                "name" => "child_of",
                "label" => "Child Of",
                "help" => "Only include terms that are direct children of the specified term ID. If this is 0, the term will be included regardless of its parent.",
            ],
            [
                "section" => "advanced",
                "order" => 12,
                "type" => "text",
                "name" => "meta_key",
                "label" => "Meta Key",
                "help" => "The meta key to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 13,
                "type" => "text",
                "name" => "meta_value",
                "label" => "Meta Value",
                "help" => "The meta value to use for filtering",
            ],
            [
                "section" => "advanced",
                "order" => 14,
                "type" => "text",
                "name" => "meta_compare",
                "label" => "Meta Compare",
                "help" => "The comparison operator to use for the meta value",
            ],
            [
                "section" => "advanced",
                "order" => 17,
                "type" => "text",
                "name" => "hide_empty",
                "label" => "Hide Empty",
                "help" => "Whether to hide terms not assigned to any posts",
            ]
        ],
        "order" => 33,
        "keywords" => "terms,taxonomy",
        "common" => true
    ],
    'range' => [
        "label" => "Range",
        "class" => Type\RangeType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/range.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "number",
                "name" => "attr[min]",
                "label" => "Minimum",
                "help" => "The minimum value of the range",
            ],
            [
                "section" => "basic",
                "order" => 2,
                "type" => "number",
                "name" => "attr[max]",
                "label" => "Maximum",
                "help" => "The maximum value of the range",
            ],
        ],
        "order" => 33,
        "keywords" => "range,numbers",
        "common" => false
    ],
    'recaptcha' => [
        "label" => "Recaptcha V2",
        "class" => Types\ReCaptchaType::class,
        "docs" => "",
        "inherited" => ["label", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "key",
                "label" => "Key",
                "help" => "The site key for the reCAPTCHA",
            ],
            [
                "section" => "basic",
                "order" => 2,
                "type" => "text",
                "name" => "secret",
                "label" => "Secret",
                "help" => "The secret key for the reCAPTCHA",
            ]
        ],
        "order" => 33,
        "keywords" => "captcha,recaptcha",
        "common" => true
    ],
    'rating' => [
        "label" => "Rating",
        "class" => Types\RatingType::class,
        "docs" => "",
        "inherited" => ["name", "label", "invalid_message", "required", "attr"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "label1",
                "label" => "Star 1 Label",
                "help" => "The label for the first star",
            ],
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "label2",
                "label" => "Star 2 Label",
                "help" => "The label for the second star",
            ],
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "label3",
                "label" => "Star 3 Label",
                "help" => "The label for the third star",
            ],
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "label4",
                "label" => "Star 4 Label",
                "help" => "The label for the fourth star",
            ],
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "label5",
                "label" => "Star 5 Label",
                "help" => "The label for the fifth star",
            ],
            [
                "section" => "basic",
                "order" => 1,
                "type" => "text",
                "name" => "rating",
                "label" => "Default Value",
                "help" => "The default value for the rating",
            ]
        ],
        "order" => 33,
        "keywords" => "captcha,recaptcha",
        "common" => true
    ],
    'tel' => [
        "label" => "Phone",
        "class" => Type\TelType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/tel.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [],
        "order" => 5,
        "keywords" => "phone,telephone,tel",
        "common" => true
    ],
    'color' => [
        "label" => "Color",
        "class" => Type\ColorType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/color.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 3,
                "type" => "checkbox",
                "name" => "html5",
                "label" => "Html5",
                "help" => "When this option is set to true, the form type checks that its value matches the HTML5 color format (/^#[0-9a-f]{6}$/i)",
            ],
        ],
        "order" => 33,
        "keywords" => "color",
        "common" => false
    ],
    'choice' => [
        "label" => "Choice",
        "class" => Type\ChoiceType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/choice.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "repeater",
                "name" => "choices",
                "fields" => [
                    [
                        "order" => 1,
                        "type" => "text",
                        "name" => "label",
                        "label" => "Label",
                    ],
                    [
                        "order" => 2,
                        "type" => "text",
                        "name" => "value",
                        "label" => "Value",
                    ],
                    [
                        "order" => 3,
                        "type" => "checkbox",
                        "name" => "selected",
                        "label" => "Selected",
                    ]
                ],
                "label" => "Choices",
                "help" => "Enter the choices for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "placeholder",
                "label" => "Placeholder",
                "help" => "The placeholder for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "preferred_choices",
                "label" => "Preferred Choices",
                "help" => "A comma separated list of choices that should be pre-selected",
            ],
        ],
        "order" => 5,
        "keywords" => "choice,select,check",
        "common" => true
    ],
    'country' => [
        "label" => "Country",
        "class" => Type\CountryType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/country.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "checkbox",
                "name" => "alpha3",
                "help" => 'If this option is true, the choice values use the <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3" target="_blank">ISO 3166-1 alpha-3</a> three-letter codes (e.g. New Zealand = NZL) instead of the default <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" target="_blank">ISO 3166-1 alpha-2</a> two-letter codes (e.g. New Zealand = NZ).',
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "placeholder",
                "label" => "Placeholder",
                "help" => "The placeholder for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "preferred_choices",
                "label" => "Preferred Choices",
                "help" => "A comma separated list of choices that should be pre-selected",
            ],
        ],
        "order" => 34,
        "keywords" => "country",
        "common" => false
    ],
    'language' => [
        "label" => "Language",
        "class" => Type\LanguageType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/language.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "checkbox",
                "name" => "alpha3",
                "help" => 'If this option is true, the choice values use the <a href="https://en.wikipedia.org/wiki/ISO_639-2" target="_blank">ISO 639-2 alpha-3 (2T)</a> three-letter codes (e.g. French = fra) instead of the default <a href="https://en.wikipedia.org/wiki/ISO_639-1" target="_blank">ISO 639-1 alpha-2</a> two-letter codes (e.g. French = fr).',
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "placeholder",
                "label" => "Placeholder",
                "help" => "The placeholder for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "preferred_choices",
                "label" => "Preferred Choices",
                "help" => "A comma separated list of choices that should be pre-selected",
            ],
        ],
        "order" => 35,
        "keywords" => "language,locale",
        "common" => false
    ],
    'locale' => [
        "label" => "Locale",
        "class" => Type\LocaleType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/locale.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "placeholder",
                "label" => "Placeholder",
                "help" => "The placeholder for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "preferred_choices",
                "label" => "Preferred Choices",
                "help" => "A comma separated list of choices that should be pre-selected",
            ],
        ],
        "order" => 36,
        "keywords" => "locale,language",
        "common" => false
    ],
    'timezone' => [
        "label" => "Timezone",
        "class" => Type\TimezoneType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/timezone.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 4,
                "type" => "select",
                "name" => "input",
                "options" => [
                    "datetimezone" => "a \DateTimeZone object",
                    "intltimezone" => "an \IntlTimeZone object",
                    "string" => "String (e.g. America/New_York)",
                ],
                "label" => "Input",
                "help" => "The format of the input data - i.e. the format that the timezone is stored on your underlying object",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "placeholder",
                "label" => "Placeholder",
                "help" => "The placeholder for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "preferred_choices",
                "label" => "Preferred Choices",
                "help" => "A comma separated list of choices that should be pre-selected",
            ]
        ],
        "order" => 37,
        "keywords" => "timezone,time,location",
        "common" => false
    ],
    'currency' => [
        "label" => "Currency",
        "class" => Type\CurrencyType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/currency.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "placeholder",
                "label" => "Placeholder",
                "help" => "The placeholder for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "preferred_choices",
                "label" => "Preferred Choices",
                "help" => "A comma separated list of choices that should be pre-selected",
            ],
        ],
        "order" => 38,
        "keywords" => "currency,money",
        "common" => false
    ],
    'date' => [
        "label" => "Date",
        "class" => Type\DateType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/date.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 3,
                "type" => "select",
                "name" => "widget",
                "label" => "Widget",
                "options" => [
                    "choice" => "Choice",
                    "text" => "Text",
                    "single_text" => "Single Text",
                ],
                "default" => "single_text",
                "help" => 'The basic way in which this field should be rendered. Can be one of the following:<br/>
                    choice: renders three select inputs. The order of the selects is defined in the format option.<br/>
                    text: renders a three field input of type text (month, day, year).<br/>
                    single_text: renders a single input of type date.',
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "date_format",
                "label" => "Date Format",
                "help" => "The format of the date",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the select box allows multiple choices",
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "placeholder",
                "label" => "Placeholder",
                "help" => "The placeholder for the select box",
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "text",
                "name" => "preferred_choices",
                "label" => "Preferred Choices",
                "help" => "A comma separated list of choices that should be pre-selected",
            ]
        ],
        "order" => 6,
        "keywords" => "date,calendar",
        "common" => true
    ],
    'datetime' => [
        "label" => "DateTime",
        "class" => Types\DateTimeType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/datetime.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "select",
                "name" => "type",
                "label" => "Type",
                "options" => [
                    "datetime" => "Datetime",
                    "date" => "Date",
                    "time" => "Time",
                ],
                "default" => "datetime",
                "help" => 'Select the input type to use',
            ],
            [
                "section" => "basic",
                "order" => 1,
                "type" => "select",
                "name" => "widget",
                "label" => "Widget",
                "options" => [
                    "choice" => "Choice",
                    "text" => "Text",
                    "single_text" => "Single Text",
                ],
                "default" => "single_text",
                "help" => 'The basic way in which this field should be rendered. Can be one of the following:<br/>
                    choice: renders three select inputs. The order of the selects is defined in the format option.<br/>
                    text: renders a three field input of type text (month, day, year).<br/>
                    single_text: renders a single input of type date.',
            ],

            [
                "section" => "basic",
                "order" => 2,
                "type" => "checkbox",
                "name" => "html5",
                "label" => "Native HTML5",
                "default" => true,
                "help" => 'Disable this field if you want to customize the date with javascript',
            ],
            [
                "section" => "basic",
                "order" => 3,
                "type" => "text",
                "name" => "input_format",
                "label" => "Format",
                "default" => "Y-m-d",
                "help" => 'If the input option is set to string, this option specifies the format of the date. This must be a valid <a href="https://php.net/manual/en/function.date.php" target="blank">PHP date format</a>.',
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "date_pattern",
                "label" => "Date Pattern",
                "default" => "",
                "help" => 'A string with the date format to use.',
            ]
        ],
        "order" => 7,
        "keywords" => "date,calendar,time",
        "common" => false
    ],
    'time' => [
        "label" => "Time",
        "class" => Type\TimeType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/time.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "select",
                "name" => "widget",
                "label" => "Widget",
                "options" => [
                    "choice" => "Choice",
                    "text" => "Text",
                    "single_text" => "Single Text",
                ],
                "default" => "single_text",
                "help" => 'The basic way in which this field should be rendered. Can be one of the following:<br/>
                    choice: renders one, two (default) or three select inputs (hour, minute, second), depending on the with_minutes and with_seconds options.<br/>
                    text: renders one, two (default) or three text inputs (hour, minute, second), depending on the with_minutes and with_seconds options.<br/>
                    single_text: renders a single input of type time.',
            ],

            [
                "section" => "basic",
                "order" => 2,
                "type" => "checkbox",
                "name" => "html5",
                "label" => "Native HTML5",
                "default" => true,
                "help" => 'Disable this field if you want to customize the date with javascript',
            ],
            [
                "section" => "basic",
                "order" => 3,
                "type" => "text",
                "name" => "input_format",
                "label" => "Format",
                "default" => "H:i:s",
                "help" => 'If the input option is set to string, this option specifies the format of the time. This must be a valid <a href="https://php.net/manual/en/function.date.php" target="blank">PHP time format</a>.',
            ]
        ],
        "order" => 35,
        "keywords" => "time,clock",
        "common" => false
    ],
    'birthday' => [
        "label" => "Birthday",
        "class" => Type\BirthdayType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/birthday.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "select",
                "name" => "widget",
                "label" => "Widget",
                "options" => [
                    "choice" => "Choice",
                    "text" => "Text",
                    "single_text" => "Single Text",
                ],
                "default" => "single_text",
                "help" => 'The basic way in which this field should be rendered. Can be one of the following:<br/>
                    choice: renders three select inputs. The order of the selects is defined in the format option.<br/>
                    text: renders a three field input of type text (month, day, year).<br/>
                    single_text: renders a single input of type date. ',
            ]
        ],
        "order" => 35,
        "keywords" => "date,calendar,time",
        "common" => false
    ],
    'checkbox' => [
        "label" => "Checkbox",
        "class" => Type\CheckboxType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/checkbox.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "checkbox",
                "name" => "checked",
                "label" => "Checked",
                "default" => false,
                "help" => 'If checked, the checkbox will be checked by default.',
            ]
        ],
        "order" => 4,
        "keywords" => "checkbox",
        "common" => true
    ],
    'file' => [
        "label" => "File",
        "class" => Type\FileType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/file.html",
        "inherited" => ["name", "label", "help", "data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 5,
                "type" => "checkbox",
                "name" => "multiple",
                "label" => "Multiple",
                "help" => "Whether the file allows multiple uploads",
            ],
            [
                "section" => "basic",
                "order" => 6,
                "name" => "extensions",
                "label" => "Extensions",
                "type" => "repeater",
                "fields" => [
                    [
                        "name" => "value",
                        "label" => "Extension",
                        "type" => "text",
                    ]
                ]
            ],
            [
                "section" => "basic",
                "order" => 6,
                "name" => "mime_types",
                "label" => "Mime Types",
                "type" => "repeater",
                "fields" => [
                    [
                        "name" => "value",
                        "label" => "Mime Type",
                        "type" => "text"
                    ]
                ],
                "help" => "This option allows you to validate a custom mime type<br/>Default: keep empty to use only extension"
            ],
            [
                "section" => "basic",
                "order" => 7,
                "name" => "extensions_message",
                "label" => "Extensions Message",
                "type" => "text",
                "help" => "The message displayed if the extension of the file is not a valid extension per the extensions option.<br/>Default: The extension of the file is invalid ({{ extension }}). Allowed extensions are {{ extensions }}"
            ],
            [
                "section" => "basic",
                "order" => 8,
                "name" => "mime_types_message",
                "label" => "Mime Types Message",
                "type" => "text",
                "help" => "The message displayed if the mimetype of the file is not a valid.<br/>Default: The mime type of the file is invalid ({{ type }}). Allowed mime types are {{ types }}."
            ],
            [
                "section" => "advanced",
                "order" => 6,
                "name" => "upload_error_message",
                "label" => "Upload Error Message",
                "type" => "text",
                "help" => "The message that is displayed if the uploaded file could not be uploaded for some unknown reason.<br/>Default: The file could not be uploaded."
            ],
            [
                "section" => "advanced",
                "order" => 7,
                "name" => "max_size",
                "label" => "Max Size",
                "type" => "text",
                "help" => "If set, the size of the underlying file must be below this file size in order to be valid. <br/>Default: Configured by system"
            ],
            [
                "section" => "advanced",
                "order" => 8,
                "name" => "max_size_message",
                "label" => "Max Size Message",
                "type" => "text",
                "help" => "The message displayed if the file is larger than the maxSize option."
            ],
            [
                "section" => "advanced",
                "order" => 11,
                "name" => "not_found_message",
                "label" => "Not Found Message",
                "type" => "text",
                "help" => "The message displayed if no file can be found at the given path.<br/>Default: The file could not be found."
            ],
            [
                "section" => "advanced",
                "order" => 12,
                "name" => "not_readable_message",
                "label" => "Not Readable Message",
                "type" => "text",
                "help" => "The message displayed if the file is not readable.<br/>Default: The file is not readable."
            ],
            [
                "section" => "advanced",
                "order" => 13,
                "name" => "upload_cant_write_error_message",
                "label" => "Upload Can't Write Error Message",
                "type" => "text",
                "help" => "The message that is displayed if the uploaded file can't be stored in the temporary folder.<br/>Default: Cannot write temporary file to disk."
            ],
            [
                "section" => "advanced",
                "order" => 14,
                "name" => "disallow_empty_message",
                "label" => "Disallow Empty Message",
                "type" => "text",
                "help" => "This constraint checks if the uploaded file is empty (i.e. 0 bytes). If it is, this message is displayed<br/>Default: An empty file is not allowed"
            ],
            [
                "section" => "advanced",
                "order" => 15,
                "name" => "upload_form_size_error_message",
                "label" => "Upload Form Size Error Message",
                "type" => "text",
                "help" => "The message that is displayed if the uploaded file is larger than allowed by the HTML file input field.<br/>Default: The file is too large"
            ],
            [
                "section" => "advanced",
                "order" => 16,
                "name" => "upload_ini_size_error_message",
                "label" => "Upload Ini Size Error Message",
                "type" => "text",
                "help" => "The message that is displayed if the uploaded file is larger than the upload_max_filesize php.ini setting.<br/>Default: The file is too large. Allowed maximum size is {{ limit }} {{ suffix }}."
            ],
            [
                "section" => "advanced",
                "order" => 17,
                "name" => "upload_no_file_error_message",
                "label" => "Upload No File Error Message",
                "type" => "text",
                "help" => "The message that is displayed if no file was uploaded.<br/>Default: No file was uploaded."
            ],
            [
                "section" => "advanced",
                "order" => 18,
                "name" => "upload_partial_error_message",
                "label" => "Upload Partial Error Message",
                "type" => "text",
                "help" => "The message that is displayed if the uploaded file was only partially uploaded.<br/>Default: The uploaded file was only partially uploaded."
            ]
        ],
        "disable_constraints" => true,
        "order" => 7,
        "keywords" => "file",
        "common" => true
    ],
    'radio' => [
        "label" => "Radio",
        "class" => Type\RadioType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/radio.html",
        "inherited" => ["name", "label", "help", "data", "empty_data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "checkbox",
                "name" => "checked",
                "label" => "Checked",
                "default" => false,
                "help" => 'If checked, the radio will be checked by default.',
            ]
        ],
        "order" => 4,
        "keywords" => "radio",
        "common" => true
    ],
    'uuid' => [
        "label" => "UUID",
        "class" => Type\UuidType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/uuid.html",
        "inherited" => ["name", "label", "help", "data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [],
        "order" => 36,
        "keywords" => "uuid",
        "common" => false
    ],
    'ulid' => [
        "label" => "ULID",
        "class" => Type\UlidType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/ulid.html",
        "inherited" => ["name", "label", "help", "data", "required", "disabled", "attr", "help_attr", "help_html", "label_attr", "label_html", "row_attr", "sanitize_html", "trim", "invalid_message"],
        "properties" => [],
        "order" => 37,
        "keywords" => "ulid",
        "common" => false
    ],
    // 'collection' => [
    //     "label" => "Collection",
    //     "class" => Type\CollectionType::class,
    //     "docs" => "https://symfony.com/doc/current/reference/forms/types/collection.html",
    //     "inherited" => ["name", "label", "help", "empty_data", "attr", "help_attr", "help_html", "label_attr", "label_html", "invalid_message"],
    //     "properties" => [],
    //     "order" => 38,
    //     "keywords" => "collection",
    //     "common" => false
    // ],
    'repeater_start' => [
        "label" => "Repeater Start",
        "class" => Types\RepeaterStartType::class,
        "docs" => "",
        "inherited" => ["name", "label"],
        "order" => 38,
        "disable_constraints" => true,
        "keywords" => "collection,repeater",
        "common" => false
    ],
    'repeater_end' => [
        "label" => "Repeater End",
        "class" => Types\RepeaterEndType::class,
        "docs" => "",
        "order" => 38,
        "keywords" => "collection,repeater",
        "common" => false,
        "properties" => [
            [
                "section" => "basic",
                "order" => 1,
                "type" => "checkbox",
                "name" => "allow_add",
                "label" => "Allow Add",
                "default" => false,
                "help" => 'If checked, new items can be added to the repeater.',
            ],
            [
                "section" => "basic",
                "order" => 2,
                "type" => "text",
                "name" => "allow_label",
                "label" => "Allow Label",
                "default" => "Add",
                "help" => 'The label for the add button.',
            ],
            [
                "section" => "basic",
                "order" => 3,
                "type" => "checkbox",
                "name" => "allow_delete",
                "label" => "Allow Delete",
                "default" => false,
                "help" => 'If checked, items can be deleted from the repeater.',
            ],
            [
                "section" => "basic",
                "order" => 4,
                "type" => "text",
                "name" => "delete_label",
                "label" => "Delete Label",
                "default" => "Delete",
                "help" => 'The label for the delete button.',
            ],
            [
                "section" => "basic",
                "order" => 5,
                "type" => "number",
                "name" => "min",
                "label" => "Minimum",
                "default" => "0",
                "help" => 'The minimum number of items that can be added to the repeater.',
            ],
            [
                "section" => "basic",
                "order" => 6,
                "type" => "number",
                "name" => "max",
                "label" => "Maximum",
                "default" => "-1",
                "help" => 'The maximum number of items that can be added to the repeater, (-1 for unlimited).',
            ],
            [
                "section" => "advanced",
                "order" => 2,
                "type" => "text",
                "name" => "min_message",
                "label" => "Minimum Message",
                "default" => 'You must have at least {{value}} items',
                "help" => 'The message to display when the minimum number of items is not met.',
            ],
            [
                "section" => "advanced",
                "order" => 3,
                "type" => "text",
                "name" => "max_message",
                "label" => "Maximum Message",
                "default" => 'You can only have {{value}} items',
                "help" => 'The message to display when the maximum number of items is exceeded.',
            ],

        ],
        "disable_constraints" => true,
    ],
    'hidden' => [
        "label" => "Hidden",
        "class" => Type\HiddenType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/hidden.html",
        "inherited" => ["name", "label", "data",  "empty_data", "required", "attr", "row_attr", "invalid_message"],
        "properties" => [],
        "order" => 39,
        "keywords" => "hidden",
        "common" => false
    ],
    'button' => [
        "label" => "Button",
        "class" => Type\ButtonType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/button.html",
        "inherited" => ["name", "label",  "label_html", "disabled", "attr", "row_attr"],
        "order" => 10,
        "keywords" => "button",
        "common" => true
    ],
    'reset' => [
        "label" => "Reset Button",
        "class" => Type\ResetType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/reset.html",
        "inherited" => ["name", "label",  "label_html", "disabled", "attr", "row_attr"],
        "order" => 37,
        "keywords" => "button,reset",
        "common" => false
    ],
    'submit' => [
        "label" => "Submit Button",
        "class" => Type\SubmitType::class,
        "docs" => "https://symfony.com/doc/current/reference/forms/types/submit.html",
        "inherited" => ["name", "label",  "label_html", "disabled", "attr", "row_attr"],
        "order" => 10,
        "keywords" => "button,submit",
        "common" => true
    ]
];
